# https://jpanther.github.io/congo/docs/configuration/#configuration

title = "Kai Kühne"

[params.author]
name = "Kai Kühne"
image = "img/author.jpg"
headline = "Software Engineer (M.Sc.)"
bio = "A little bit about me"
links = [
# { github = "https://github.com/username" },
# { linkedin="google.com" },
]

