# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

# https://jpanther.github.io/congo/docs/getting-started/#colour-schemes
colorScheme = "cherry"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = false

article.showDateUpdated	 = true
article.showAuthor = false

[homepage]
layout = "profile"
showRecent = false

[footer]
showThemeAttribution = false
showAppearanceSwitcher = true

